### ISSUE TITLE
STDERR: invalid tag

### ISSUE THREAD

**Issue by JannikZed** [gdraheim/docker-copyedit#5]
When trying to remove a certain port of an image, I only receive this error in the last step of the process:
```
DEBUG:edit:changed 1 layer metadata
ERROR:edit:CMD docker load -i load.tmp/ready.tar
ERROR:edit:EXIT 1
ERROR:edit:STDOUT
ERROR:edit:STDERR invalid tag "jannikz/gluster-prod"

Traceback (most recent call last):
  File "./docker-copyedit.py", line 706, in <module>
    edit_image(inp, out, commands)
  File "./docker-copyedit.py", line 252, in edit_image
    sh(cmd.format(**locals()))
  File "./docker-copyedit.py", line 43, in sh
    raise Exception("shell command failed")
Exception: shell command failed
```
No matter what tag I'm entering .. did you ever face a problem like this? 

```
./docker-copyedit.py \
FROM jannikz/gluster-prod:latest INTO jannikz/gluster-prod -vvv REMOVE PORT 111
DEBUG:edit:image parsing = jannikz/gluster-prod:latest
DEBUG:edit:.registry = None
DEBUG:edit:.image = jannikz/gluster-prod
DEBUG:edit:.tag = :latest
DEBUG:edit:image parsing = jannikz/gluster-prod
DEBUG:edit:.registry = None
DEBUG:edit:.image = jannikz/gluster-prod
DEBUG:edit:.tag = None
DEBUG:edit:total 1484224
```

`__version__ = "1.2.1402"` 
`Docker version 18.06.1-ce, build e68fc7a`

**Comment by gdraheim** [comment]
I have created a testcase for it and it did show that my initial assumption was quite right .... the missing ":latest" version tag did lead into the problems. So the implementation  has now changed to simply add it when it is missing on the command line.

fixed in the latest release.

**Comment by gdraheim** [comment]
... assuming fixed.
